import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

export const ACTIVITY_START = "<!-- AUTO:ACTIVITY:START -->";
export const ACTIVITY_END = "<!-- AUTO:ACTIVITY:END -->";

function escapeCell(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function badgeSegment(value) {
  return encodeURIComponent(String(value).replaceAll("-", "--").replaceAll("_", "__").replaceAll(" ", "_"));
}

const TECH_STYLES = {
  Python: { logo: "python", color: "3776AB" },
  PyTorch: { logo: "pytorch", color: "EE4C2C" },
  TensorFlow: { logo: "tensorflow", color: "FF6F00" },
  "Scikit-Learn": { logo: "scikitlearn", color: "F7931E" },
  OpenCV: { logo: "opencv", color: "5C3EE8" },
  Pandas: { logo: "pandas", color: "150458" },
  NumPy: { logo: "numpy", color: "013243" },
  JavaScript: { logo: "javascript", color: "F7DF1E", logoColor: "black" },
  Git: { logo: "git", color: "F05032" },
  SQL: { color: "4479A1" },
  Docker: { logo: "docker", color: "2496ED" }
};

function renderLinks(links) {
  return links.map((link) => {
    const logo = link.logo ? `&logo=${encodeURIComponent(link.logo)}&logoColor=white` : "";
    const image = `https://img.shields.io/badge/${badgeSegment(link.label)}-${badgeSegment(link.value)}-${link.color}?style=for-the-badge${logo}`;
    return `  <a href="${link.url}"><img alt="${link.label}" src="${image}"></a>`;
  }).join("\n");
}

function renderTechStack(techStack) {
  return techStack.map((item) => {
    const style = TECH_STYLES[item] || { color: "374151" };
    const logo = style.logo ? `&logo=${encodeURIComponent(style.logo)}` : "";
    const logoColor = style.logo ? `&logoColor=${style.logoColor ?? "white"}` : "";
    const image = `https://img.shields.io/badge/${badgeSegment(item)}-${style.color}?style=for-the-badge${logo}${logoColor}`;
    return `  <img src="${image}" alt="${escapeCell(item)}" />`;
  }).join("\n");
}

function renderFocus(focus) {
  return focus.map((item) => `- **${escapeCell(item.name)}** — ${escapeCell(item.description)}`).join("\n");
}

function renderProjects(projects) {
  return projects.map((project) => {
    const homepage = project.homepage ? ` ([Live](${project.homepage}))` : "";
    return `- **[${escapeCell(project.name)}](${project.url})** — _${escapeCell(project.focus)}_. ${escapeCell(project.summary)}${homepage}`;
  }).join("\n");
}

function extractActivity(readme) {
  const startIndex = readme.indexOf(ACTIVITY_START);
  const endIndex = readme.indexOf(ACTIVITY_END);
  if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) return null;
  return readme.slice(startIndex + ACTIVITY_START.length, endIndex).trim();
}

async function readExistingActivity(readmePath) {
  try {
    const existing = await readFile(readmePath, "utf8");
    return extractActivity(existing);
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

export async function generateProfileReadme({ config, manifest, readmePath }) {
  const existingActivity = await readExistingActivity(readmePath);
  const activity = existingActivity || "_Recent public activity will appear here after the workflow runs._";
  const activitySection = config.activity.enabled
    ? `\n## Recent Activity\n\n${ACTIVITY_START}\n${activity}\n${ACTIVITY_END}\n`
    : "";
  const techStack = renderTechStack(config.techStack);
  const focusItems = renderFocus(config.focus);
  const projectItems = renderProjects(config.projects);
  const about = config.profile.about.join("\n\n");
  const username = config.profile.username;

  const readme = `<!-- Generated by GitHub Profile Agent Console. Edit profile.config.json, then run npm run generate. -->
<p align="center">
  <picture>
    <source media="(max-width: 760px) and (prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.mobileDark}">
    <source media="(max-width: 760px)" srcset="./assets/hero/${manifest.assets.mobileLight}">
    <source media="(prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.desktopDark}">
    <source media="(prefers-color-scheme: light)" srcset="./assets/hero/${manifest.assets.desktopLight}">
    <img src="./assets/hero/${manifest.assets.desktopDark}" alt="${config.profile.name} - ${config.profile.headline}" width="100%">
  </picture>
</p>

<h1 align="center">${config.profile.name}</h1>

<h3 align="center">${config.profile.headline}</h3>

<p align="center">
  ${config.profile.affiliation} · ${config.profile.location}
</p>

<p align="center">
${renderLinks(config.links)}
</p>

<p align="center">
  <img src="https://visitor-badge.laobi.icu/badge?page_id=${username}.${username}&" alt="Visitor Badge" />
  &nbsp;
  <code>${config.profile.status}</code>
</p>

<p align="center">
  <img src="./assets/terminal-typing.svg" alt="terminal: waldy@github" width="100%" />
</p>

---

## About

${about}

**Where I'm investing time:**

${focusItems}

## Featured Work

${projectItems}

---

## Tech Stack

<p align="center">
${techStack}
</p>

---

## GitHub Stats

<div align="center">
  <img src="https://github-readme-stats.vercel.app/api?username=${username}&show_icons=true&theme=tokyonight&hide_border=true&count_private=true" height="180" alt="GitHub stats" />
  <img src="https://github-readme-stats.vercel.app/api/top-langs/?username=${username}&layout=compact&theme=tokyonight&hide_border=true" height="180" alt="Top languages" />
</div>

<div align="center">
  <img src="https://streak-stats.demolab.com?user=${username}&locale=en&mode=daily&theme=tokyonight&hide_border=true&border_radius=5&order=3" height="180" alt="streak graph" />
</div>

<p align="center">
  <img src="https://github-profile-trophy.vercel.app/?username=${username}&theme=tokyonight&no-frame=true&column=4&row=2" alt="GitHub trophies" />
</p>

---
 
<p align="center">
  <img src="https://raw.githubusercontent.com/${username}/${username}/output/snake.svg" alt="Snake animation" width="100%" />
</p>
${activitySection}
---

<p align="center">
  ${config.footer}
</p>
`;

  await writeFile(resolve(readmePath), readme);
  return readme;
}
